server:
  port: 8081
spring:
  application:
    name: "application-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  flyway:
    url: "jdbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,mappings"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: "Sikret00-2$$_32.,/>>/SfgdskjlXDSF<>????94534906--=_+)I-w=5243=0-59=4+_)I*(+"
routes:
  paths:
    base: "/api/v1"
    application: "/applications"
    applicationsToReview: "/applications/manual_review"
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5432}"
    database: "${DB_NAME:application}"
    username: "${DB_USER:crediya}"
    password: "${DB_PASSWORD:P@55w0rd}"
adapter:
  restconsumer:
    timeout: 5000
    url: "${AUTH_API_URL:http://localhost:8080}"
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/343629588964/application-notifications-queue"
logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: "TRACE"
resilience4j:
  circuitbreaker:
    instances:
      findUserByIdNumber:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      findUserByIdIn:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
